application: manager
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets

- url: /.*
  script: telebits.app
  secure: always

libraries:
- name: jinja2
  version: latest

- name: django
  version: latest